name:
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Test
        run: go test -v ./pkg/... -coverprofile cover.out

      - name: Convert report
        run: |
          go test -v ./pkg/... -coverprofile cover.out
          go get github.com/t-yuki/gocover-cobertura
          gocover-cobertura < cover.out > coverage.xml

      - name: Codacy
        env:
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
        run: |
          bash <(curl -Ls https://coverage.codacy.com/get.sh) report \
            --force-coverage-parser go -r cover.out
